const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const checks=[];
function fixture(options={}){
 let time=10000,c,fitModel=null,inferModel=null;const queue=[],scheduled=[],out=[],nativeCalls=[],dicts={},datasets={},buffers={'101-gesture-input':Array(5).fill(0)},writes=[],files={};
 const db={10:{type:'Device',name:'Glove Gesture'},21:{type:'DeviceParameter',name:'Device On',min:0,max:1,value:0,is_quantized:1,is_enabled:1,value_items:['Off','On']},22:{type:'DeviceParameter',name:'Plug-in Switch',min:0,max:1,value:0,is_quantized:0,is_enabled:1},23:{type:'DeviceParameter',name:'Frequency',min:20,max:20000,value:1000,is_quantized:0,is_enabled:1},24:{type:'DeviceParameter',name:'Mode',min:0,max:3,value:0,is_quantized:1,is_enabled:1,value_items:['a','b','c','d']}};
 function LiveAPI(cb,p){this.id=p==='this_device'?10:Number(p.split(' ')[1]);this.type=(db[this.id]||{}).type;this.get=k=>{if(!db[this.id]||!(k in db[this.id]))throw Error('Missing property');const v=db[this.id][k];return Array.isArray(v)?v:[v];};this.set=(k,v)=>{if(!db[this.id]?.is_enabled)throw Error('Disabled');db[this.id][k]=v;writes.push([this.id,k,v]);};}
 function Task(fn){this.fn=fn;this.cancel=()=>{this.cancelled=true;};this.schedule=()=>scheduled.push(this);this.repeat=()=>{};}
 function Dict(n){this.name=n;this.parse=s=>{dicts[n]=JSON.parse(s);};this.stringify=()=>JSON.stringify(dicts[n]);this.freepeer=()=>{};}
 function MaxBuffer(n){this.framecount=()=>buffers[n].length;this.poke=(ch,start,v)=>{assert.equal(ch,1);buffers[n]=v.map(Math.fround);};this.freepeer=()=>{};}
 function File(n,access){this.isopen=access==='write'||n in files;this.position=0;this.text=access==='write'?'':files[n]||'';this.eof=this.text.length;this.readstring=l=>{const s=this.text.slice(this.position,this.position+l);this.position+=s.length;return s;};this.writestring=s=>{this.text+=s;this.position+=s.length;};this.close=()=>{if(access==='write')files[n]=this.text;};}
 const respond=(lane,args)=>{if(!options.silent)queue.push(()=>vm.runInContext('backend.receive('+JSON.stringify(lane)+','+JSON.stringify(args)+')',c));};
 function native(name){return {message:(method,...args)=>{
  nativeCalls.push({name,method,args});if(name==='input-buffer'){assert.equal(method,'sizeinsamps');buffers['101-gesture-input']=Array(args[0]).fill(0);return;}
  if(name==='data-input'||name==='data-labels'){if(method==='load'){datasets[name]=dicts[args[1]];respond(name==='data-input'?'input':'labels',['load']);}return;}
  if(name==='classifier-train'){
   if(method==='fit'){assert(datasets['data-input']&&datasets['data-labels']);const x=datasets['data-input'],y=datasets['data-labels'],labels=[...new Set(Object.values(y.data).map(v=>v[0]))];
    // Lifecycle-only native fixture. Neural accuracy is tested separately in C++.
    fitModel={mlp:{layers:[{rows:x.cols,cols:labels.length,activation:1,biases:labels.map(()=>0),weights:Array.from({length:x.cols},()=>labels.map(()=>0))}]},labels:{rows:labels.length,labels}};respond('train',['fit',...args,.01*labels.length]);
   }else if(method==='dump'){dicts.dump=fitModel;respond('train',['dump','dictionary','dump']);}return;
  }
  if(name==='classifier-infer'){
   if(method==='cols')respond('infer',['cols',0]);else if(method==='load'){inferModel=JSON.parse(JSON.stringify(dicts[args[1]]));respond('infer',['load']);}
   else if(method==='predictpoint')respond('infer',['predictpoint',...args,options.label||inferModel.labels.labels[0]]);
  }
 }};}
 const patcher={filepath:'/test/Glove Gesture.maxpat',getnamed:n=>native(n)};
 function FakeDate(...a){return new Date(...(a.length?a:[time]));}FakeDate.parse=Date.parse;FakeDate.now=()=>time;FakeDate.prototype=Date.prototype;
 c={LiveAPI,Task,Dict,Buffer:MaxBuffer,File,Date:FakeDate,jsarguments:['gesture_control.js',101],patcher,outlet:(...a)=>out.push(a),post:()=>{},console};vm.createContext(c);vm.runInContext('function arrayfromargs(a){return Array.prototype.slice.call(a && typeof a.length==="number" ? a : arguments);}',c);
 vm.runInContext(fs.readFileSync(path.join(__dirname,'../Glove_Gesture/gesture_control.js'),'utf8'),c);
 const plain=v=>JSON.parse(JSON.stringify(v));const exec=s=>vm.runInContext(s,c);
 function drain(max=100000){let n=0;while(queue.length||scheduled.length){if(++n>max)throw Error('Native fixture did not settle');if(queue.length)queue.shift()();else{const t=scheduled.shift();if(!t.cancelled)t.fn();}}}
 function send(value){c.command(encodeURIComponent(JSON.stringify(value)));}
 c.bang();drain();send({op:'hello'});
 return {c,db,out,nativeCalls,queue,scheduled,files,writes,send,drain,exec,plain,advance:n=>{time+=n;},time:()=>time,frame:(hand,a)=>c[hand](...a),state:()=>{const row=out.filter(x=>x[0]===0&&x[1]==='statepacket').at(-1);return JSON.parse(decodeURIComponent(row[5]));}};
}
function setup(f,mode='left'){
 f.send({op:'mode',value:mode});f.exec("banks[mode].enabled=[true,false,false,false,false,false];for(var k=0;k<20;k++){banks[mode].samples.push({x:Array(Gesture.dim(mode)).fill(0),label:'open',trial:'a'},{x:Array(Gesture.dim(mode)).fill(.5),label:'other',trial:'b'});}");
 f.frame('left',Array(5).fill(0));f.frame('right',Array(5).fill(0));f.send({op:'setting',key:'epochs',value:50});f.send({op:'train'});f.drain();assert(f.c.bank().model);
}
function observed(f,label,x=Array(5).fill(0)){f.c.prediction(label,f.exec(JSON.stringify(x)),f.exec('({epoch:runEpoch,mode:mode,time:now()})'));}
function test(name,fn){fn();checks.push(name);}
test('Native readiness and isolated buffer/model names',()=>{const f=fixture();assert(f.c.backend.available);assert(f.nativeCalls.some(x=>x.method==='cols'));assert.equal(f.c.backend.names.input,'101-gesture-input');});
test('Two-second recording captures fresh frames at 20 Hz with trial IDs',()=>{const f=fixture();f.frame('left',[0,0,0,0,0]);f.send({op:'record',label:'open'});for(let i=0;i<40;i++){f.advance(50);f.frame('left',[.1,.2,.3,.4,.5]);}assert.equal(f.c.bank().samples.length,39);assert.equal(new Set(f.c.bank().samples.map(x=>x.trial)).size,1);assert.equal(f.c.recording,null);});
test('No repeated sample capture from stale data',()=>{const f=fixture();f.frame('left',[0,0,0,0,0]);f.send({op:'record',label:'fist'});f.advance(2000);f.c.tick();assert.equal(f.c.bank().samples.length,0);});
test('Left Right Both have independent banks and Both requires synchronization',()=>{const f=fixture();f.frame('left',[0,.1,.2,.3,.4]);f.send({op:'record',label:'open'});f.advance(50);f.frame('left',[0,.1,.2,.3,.4]);f.send({op:'mode',value:'right'});assert.equal(f.c.bank().samples.length,0);f.frame('right',[.1,.2,.3,.4,.5]);f.send({op:'record',label:'open'});f.advance(50);f.frame('right',[.1,.2,.3,.4,.5]);f.send({op:'mode',value:'both'});f.advance(100);f.frame('left',[0,.1,.2,.3,.4]);assert.throws(()=>f.c.fresh(f.time()));f.frame('right',[.1,.2,.3,.4,.5]);assert.deepEqual(f.plain(f.c.fresh(f.time())),[0,.1,.2,.3,.4,.1,.2,.3,.4,.5]);});
test('Train requires minimum examples for each enabled pose and Other',()=>{const f=fixture();f.send({op:'train'});assert.match(f.c.note,/Open hand/);f.exec('banks.left.enabled=[false,false,false,false,false,false]');f.send({op:'train'});assert.match(f.c.note,/at least one/);f.exec('banks.left.enabled[0]=true;for(var k=0;k<20;k++)banks.left.samples.push({x:[0,0,0,0,0],label:"open",trial:"a"})');f.send({op:'train'});assert.match(f.c.note,/Other/);});
test('Both native dataset load acknowledgements precede fit',()=>{const f=fixture();setup(f);assert.equal(f.nativeCalls.find(x=>x.name==='data-labels'&&x.method==='load').args[0],'dictionary');assert(f.nativeCalls.some(x=>x.method==='fit'));assert.equal(f.c.bank().model.labels.rows,2);assert.equal(f.c.trainer,null);assert(!f.c.running);});
test('Deferred model load gates predictpoint; repeated frames coalesce',()=>{const f=fixture();setup(f);f.send({op:'run'});assert.equal(f.c.backend.operation.kind,'load');f.advance(20);f.frame('left',Array(5).fill(.01));f.advance(20);f.frame('left',Array(5).fill(.02));assert.equal(f.c.backend.pending.x[0],.02);f.drain();assert(f.nativeCalls.some(x=>x.method==='predictpoint'));});
test('Stable pose toggles once; jitter and held pose do not retrigger',()=>{const f=fixture();setup(f);f.c.mapped(0,'id',21);f.send({op:'run'});f.drain();for(let i=0;i<20;i++){f.advance(20);f.frame('left',Array(5).fill(0));f.drain();}assert.equal(f.db[21].value,1);assert.equal(f.writes.length,1);assert.equal(f.c.temporal.confirmed,'open');});
test('Distance rejects an unfamiliar pose instead of firing',()=>{const f=fixture();setup(f);f.c.mapped(0,'id',21);f.frame('left',Array(5).fill(1));f.send({op:'run'});f.drain();for(let i=0;i<10;i++){f.advance(20);f.frame('left',Array(5).fill(1));f.drain();}assert.equal(f.db[21].value,0);assert.equal(f.c.candidate,'other');assert.equal(f.c.distance,1);});
test('Pulse returns off after the configured duration',()=>{const f=fixture();setup(f);f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'pulse'});f.c.actionEnter('open',f.time());assert.equal(f.db[21].value,1);f.advance(121);f.c.tick();assert.equal(f.db[21].value,0);assert.equal(Object.keys(f.c.owned).length,0);});
test('Hold releases on gesture exit, Stop and data loss',()=>{for(const action of ['exit','stop','loss']){const f=fixture();setup(f);f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'gate'});f.send({op:'run'});f.drain();f.c.actionEnter('open',f.time());f.exec("temporal.confirmed='open'");if(action==='exit')f.c.actionExit('open');else if(action==='stop')f.send({op:'stop'});else{f.advance(301);f.c.tick();}assert.equal(f.db[21].value,0);}});
test('On and Off actions remain intentional states after Stop',()=>{const f=fixture();f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'on'});f.c.actionEnter('open',f.time());f.send({op:'stop'});assert.equal(f.db[21].value,1);f.send({op:'action',index:0,value:'off'});f.c.actionEnter('open',f.time());assert.equal(f.db[21].value,0);});
test('Temporary release respects a manually changed button',()=>{const f=fixture();f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'gate'});f.c.actionEnter('open',f.time());f.db[21].value=0;const count=f.writes.length;f.send({op:'stop'});assert.equal(f.writes.length,count);});
test('A later action for a shared target cancels an earlier pulse timer',()=>{const f=fixture();f.c.mapped(0,'id',21);f.c.mapped(1,'id',21);f.send({op:'action',index:0,value:'pulse'});f.send({op:'action',index:1,value:'on'});f.c.actionEnter('open',f.time());f.c.actionEnter('fist',f.time());f.advance(200);f.c.tick();assert.equal(f.db[21].value,1);});
test('Remap releases the previous held target and stops Run',()=>{const f=fixture();setup(f);f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'gate'});f.send({op:'run'});f.drain();f.c.actionEnter('open',f.time());f.c.mapped(0,'id',22);assert.equal(f.db[21].value,0);assert(!f.c.running);assert.equal(f.c.mappings[0].id,22);});
test('Non-button ranges, deleted and disabled targets are rejected',()=>{const f=fixture();f.c.mapped(0,'id',23);assert.equal(f.c.mappings[0],null);f.c.mapped(0,'id',24);assert.equal(f.c.mappings[0],null);f.c.mapped(0,'id',21);f.db[21].is_enabled=0;f.c.actionEnter('open',f.time());assert.equal(f.db[21].value,0);assert.equal(f.c.mappings[0],null);f.c.mapped(1,'id',22);delete f.db[22];f.c.actionEnter('fist',f.time());assert.equal(f.c.mappings[1],null);});
test('Mode change and Stop discard late native results',()=>{const f=fixture();setup(f);f.c.mapped(0,'id',21);f.send({op:'run'});f.send({op:'mode',value:'right'});f.drain();assert.equal(f.db[21].value,0);assert(!f.c.running);assert.equal(f.c.candidate,'other');});
test('Invalid frames stop Run and clear freshness',()=>{const f=fixture();setup(f);f.send({op:'run'});f.drain();f.frame('left',[0,0,0,0,NaN]);assert(!f.c.running);assert.equal(f.c.frameTimes.left,0);});
test('Cancel drains the old native training request before another job',()=>{const f=fixture();setup(f);f.send({op:'train'});assert(f.c.backend.job);f.send({op:'train'});assert.equal(f.c.trainer,null);f.send({op:'train'});assert.match(f.c.note,/previous native/);f.drain();assert.equal(f.c.backend.job,null);assert(f.c.bank().model);});
test('Named model save/load isolates snapshots and enforces hand mode',()=>{const f=fixture();setup(f);f.send({op:'saveModel',name:'张手 / 模型'});const id=f.c.modelSelection;f.exec('banks.left.samples[0].x[0]=.3');assert.equal(f.c.models[0].bank.samples[0].x[0],0);f.send({op:'loadModel',id});assert.equal(f.c.bank().samples[0].x[0],0);f.send({op:'mode',value:'right'});f.send({op:'loadModel',id});assert.match(f.c.note,/left mode/);});
test('Live Set state restores all banks and settings with Run off; mappings stay native',()=>{const f=fixture();setup(f,'both');f.send({op:'saveModel',name:'Pair'});f.send({op:'setting',key:'hold',value:160});const stored=f.c.stored;assert(!decodeURIComponent(stored).includes('mapIDs'));const g=fixture();g.c.restore(stored);assert.equal(g.c.mode,'both');assert.equal(g.c.hold,160);assert.equal(g.c.models.length,1);assert(g.c.bank().model);assert(!g.c.running);g.c.mapped(0,'id',22);assert.equal(g.c.mappings[0].id,22);});
test('Unicode JSON export/import round-trips without transferring button mappings',()=>{const f=fixture();setup(f);f.send({op:'saveModel',name:'中文 / Glove'});f.send({op:'export',id:f.c.modelSelection});f.c.writemodel('/tmp/gesture model');const saved=JSON.parse(f.files['/tmp/gesture model.json']);assert.equal(saved.name,'中文 / Glove');assert(!('mappings' in saved));const g=fixture();g.files['/tmp/gesture model.json']=f.files['/tmp/gesture model.json'];g.send({op:'import'});g.c.readmodel('/tmp/gesture model.json');assert.equal(g.c.models.length,1);assert.equal(g.c.models[0].name,saved.name);assert.notEqual(g.c.models[0].id,saved.id);});
test('Malformed imported files and invalid saved state cannot replace working banks',()=>{const f=fixture();setup(f);const old=f.c.bank();f.files.bad='{"format":"glove-neural-scope-model"}';f.send({op:'import'});f.c.readmodel('bad');assert.equal(f.c.models.length,0);f.c.restore(encodeURIComponent(JSON.stringify({version:3})));assert.equal(f.c.bank(),old);assert.match(f.c.note,/Unsupported/);});
test('Missing native externals report a fault and prevent Run',()=>{const f=fixture({silent:true});f.advance(3001);f.c.tick();assert(f.c.backend.fault);assert(!f.c.backend.available);assert(!f.c.running);assert.match(f.c.note,/did not respond/);});
test('Prediction watchdog releases temporary buttons',()=>{const f=fixture();setup(f);f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'gate'});f.send({op:'run'});f.c.actionEnter('open',f.time());f.advance(3001);f.c.tick();assert(f.c.backend.fault);assert.equal(f.db[21].value,0);assert(!f.c.running);});
test('Disabled class and cleared examples invalidate only the current bank',()=>{const f=fixture();setup(f);f.send({op:'enabled',label:'open',value:false});assert.equal(f.c.bank().model,null);f.send({op:'clear',label:'open'});assert.equal(f.c.countSamples()[0],0);assert.equal(f.c.countSamples()[6],20);});
test('Disposal cancels tasks and releases temporary outputs',()=>{const f=fixture();f.c.mapped(0,'id',21);f.send({op:'action',index:0,value:'gate'});f.c.actionEnter('open',f.time());f.c.notifydeleted();assert.equal(f.db[21].value,0);assert(f.c.backend.disposed);assert(f.c.clockTask.cancelled);});
fs.writeFileSync(path.join(__dirname,'../validation/adapter.json'),JSON.stringify({kind:'Shipped controller executed with simulated Max native lifecycle and Live Object Model; not a host test',checks},null,2)+'\n');console.log(checks.length+' classification adapter/protocol checks passed');
