const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),G=require('./gesture_logic');
const checks=[];function test(name,fn){fn();checks.push(name);}
test('Left/Right use five features and Both uses ten',()=>{assert.equal(G.dim('left'),5);assert.equal(G.dim('right'),5);assert.equal(G.dim('both'),10);assert.throws(()=>G.dim('ambiguous'));});
test('Reject missing, non-finite and non-normalized glove values',()=>{for(const x of [[0,0],[0,0,0,0,NaN],[0,0,0,0,Infinity],[0,0,0,0,-.1],[0,0,0,0,1.1]])assert.throws(()=>G.vector(x,5));assert.deepEqual(G.vector([0,.25,.5,.75,1],5),[0,.25,.5,.75,1]);});
test('Hold confirms once and held gestures never retrigger',()=>{const t=new G.Temporal(120,350);assert.equal(t.feed('open',0).enter,null);assert.equal(t.feed('open',119).enter,null);assert.equal(t.feed('open',120).enter,'open');for(let n=140;n<2000;n+=20)assert.equal(t.feed('open',n).enter,null);});
test('Short label jitter is ignored; stable Other releases a held gesture',()=>{const t=new G.Temporal(120,350);t.feed('open',0);t.feed('open',120);t.feed('fist',140);t.feed('open',160);assert.equal(t.confirmed,'open');t.feed('other',180);assert.equal(t.feed('other',300).exit,'open');assert.equal(t.confirmed,'other');});
test('Cooldown delays a new gesture and re-entry is possible after exit',()=>{const t=new G.Temporal(80,350);t.feed('open',0);t.feed('open',80);t.feed('fist',100);assert.equal(t.feed('fist',180).enter,null);assert.equal(t.feed('fist',430).enter,'fist');t.feed('other',450);t.feed('other',530);t.feed('open',650);assert.equal(t.feed('open',780).enter,'open');});
test('Observation gaps do not count toward stable Hold and reset emits exit',()=>{const t=new G.Temporal(120,0);t.feed('open',0);assert.equal(t.feed('open',500).enter,null);t.feed('open',620);assert.equal(t.feed('fist',1000).exit,'open');assert.equal(t.confirmed,null);t.reset();assert.equal(t.candidate,null);});
test('Distance rejection uses RMS normalized features and the predicted class',()=>{const a=[{x:[0,0,0,0,0],label:'open'},{x:[1,1,1,1,1],label:'fist'}];assert.equal(G.distance([1,1,1,1,1],a,'fist'),0);assert.equal(G.distance([.5,.5,.5,.5,.5],a,'open'),.5);assert.equal(G.distance([0,0,0,0,0],a,'ok'),Infinity);});
test('Native classifier format validates encoder labels, dimensions and weights',()=>{const m={mlp:{layers:[{rows:5,cols:2,activation:1,biases:[0,0],weights:Array.from({length:5},()=>[0,0])}]},labels:{rows:2,labels:['open','other']}};G.model(m,5,['other','open']);assert.throws(()=>G.model(m,10));assert.throws(()=>G.model(m,5,['fist','other']));const broken=G.copy(m);broken.mlp.layers[0].weights[0][0]=Infinity;assert.throws(()=>G.model(broken,5));broken.mlp.layers[0].weights[0][0]=0;broken.labels.labels=['open','open'];assert.throws(()=>G.model(broken,5));});
test('Snapshots require gesture-specific identity and rejection examples',()=>{const b=G.bank();b.enabled=[true,false,false,false,false,false];b.samples=Array.from({length:40},(_,i)=>({x:Array(5).fill(i<20?0:.5),label:i<20?'open':'other',trial:'repeat-1'}));b.model={mlp:{layers:[{rows:5,cols:2,activation:1,biases:[0,0],weights:Array.from({length:5},()=>[0,0])}]},labels:{rows:2,labels:['open','other']}};const r={format:'glove-gesture-model',version:1,id:'m',name:'张手',savedAt:'2026-10-08T12:00:00Z',mode:'left',bank:b};G.record(r);assert.throws(()=>G.record({...r,format:'glove-neural-scope-model'}));assert.throws(()=>G.record({...r,mode:'right',bank:{...b,samples:[]}}));});
test('Capture limits and independent bank defaults',()=>{const a=G.bank(),b=G.bank();a.enabled[0]=true;assert(!b.enabled[0]);a.samples=Array.from({length:401},()=>({x:[0,0,0,0,0],label:'open',trial:'x'}));assert.throws(()=>G.validateBank(a,5));});
test('All 36 ordered pairs have unique labels, titles and independent mapping slots',()=>{const pairs=G.keys('both');assert.equal(pairs.length,36);assert.equal(new Set(pairs).size,36);assert.equal(G.pair('fist','v'),'fist__v');assert.equal(G.slot('both','fist__v'),21);assert.equal(G.slot('left','open'),0);assert.equal(G.slot('right','open'),6);assert.equal(G.title('fist__v','both'),'L Fist + R V sign');assert.throws(()=>G.pair('other','open'));assert.throws(()=>G.slot('both','fist'));});
fs.writeFileSync(path.join(__dirname,'../validation/logic.json'),JSON.stringify({kind:'Pure temporal/data/model checks; no neural optimizer in JavaScript',checks},null,2)+'\n');console.log(checks.length+' gesture logic checks passed');
