const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../Glove_Gesture/gesture_ui.html'),'utf8'),checks=[];
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);
const elements={},props={},sent=[],bindings={};
function Element(){this.dataset={};this.style={setProperty:(k,v)=>props[k]=v};this.children=[];this._text='';this.selectors={};}
Object.defineProperty(Element.prototype,'textContent',{get(){return this._text;},set(v){this._text=v;this.children=[];}});
Element.prototype.appendChild=function(e){this.children.push(e);if(e.id)elements[e.id]=e;};Element.prototype.querySelector=function(s){return this.selectors[s]||(this.selectors[s]=new Element());};
for(const id of ids)elements[id]=new Element();
const document={documentElement:{style:{setProperty:(k,v)=>props[k]=v}},activeElement:null,getElementById:id=>elements[id],createElement:()=>new Element()};
const c={document,window:{max:{outlet:(...a)=>sent.push(a),bindInlet:(k,fn)=>bindings[k]=fn}}};vm.createContext(c);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],c);
function test(n,fn){fn();checks.push(n);}
const base={mode:'left',ready:true,engineReady:true,running:false,training:false,recording:null,counts:[40,40,40,40,40,40,40],enabled:[true,true,true,true,true,true],trained:true,loss:.02,hold:120,cooldown:350,radius:.18,epochs:500,pulse:120,actions:Array(6).fill('toggle'),note:'Ready',candidate:'other',confirmed:null,colors:{},targets:Array(6).fill(''),models:[],modelSelection:''};
function state(s,seq=1){c.statepacket(seq,0,1,encodeURIComponent(JSON.stringify(s)));}
test('Six inline original hand illustrations and matching controls',()=>{assert.equal(elements.cards.children.length,6);for(const label of ['open','fist','index','v','middle','ok']){assert(c.icons[label].includes('<svg'));assert(elements['card-'+label].querySelector('.art').innerHTML.includes('<svg'));}assert.equal(JSON.parse(decodeURIComponent(sent[0][1])).op,'hello');});
test('Left mirrors the hand; Right and Both show their own orientation/pairs',()=>{state(base,1);assert(elements['card-open'].querySelector('.art').innerHTML.includes('class="left"'));state({...base,mode:'right'},2);assert(elements['card-open'].querySelector('.art').innerHTML.includes('class="right"'));state({...base,mode:'both'},3);assert.equal((elements['card-open'].querySelector('.art').innerHTML.match(/<svg/g)||[]).length,2);});
test('Missing native engine disables Run and Train',()=>{state({...base,engineReady:false},4);assert(elements.run.disabled);assert(elements.train.disabled);assert.equal(elements.engine.textContent,'FLUCOMA OFFLINE');});
test('Recording and training states prevent overlapping actions',()=>{state({...base,recording:'ok'},5);assert(elements.run.disabled);assert(elements.train.disabled);assert(elements['card-ok'].className.includes('recording'));state({...base,training:true},6);assert(elements.run.disabled);assert.equal(elements.train.textContent,'Cancel');assert(!elements.train.disabled);assert(elements.other.disabled);});
test('Confirmed/candidate cards and button targets are visibly distinguished',()=>{state({...base,confirmed:'v',candidate:'v',targets:['Device On','','','','','']},7);assert(elements['card-v'].className.includes('active'));assert(elements['card-open'].title.includes('Device On'));assert(elements['card-ok'].title.includes('contact is not measured'));});
test('Named model selection enforces hand mode while export stays available',()=>{const s={...base,models:[{id:'saved',name:'中文',mode:'both'}],modelSelection:'saved'};state(s,8);assert(elements.loadModel.disabled);assert(!elements.exportModel.disabled);state({...s,mode:'both'},9);assert(!elements.loadModel.disabled);assert.equal(elements.model.children[1].textContent,'中文 · both');});
test('Fragmented, out-of-order, duplicate and stale packets are handled',()=>{const e=encodeURIComponent(JSON.stringify({...base,note:'New packet'})),parts=e.match(/.{1,120}/g);for(let i=parts.length-1;i>0;i--)c.statepacket(10,i,parts.length,parts[i]);assert.notEqual(elements.note.textContent,'New packet');c.statepacket(10,0,parts.length,parts[0]);assert.equal(elements.note.textContent,'New packet');c.statepacket(9,0,1,encodeURIComponent(JSON.stringify(base)));assert.equal(elements.note.textContent,'New packet');c.statepacket(10,0,parts.length,parts[0]);assert.equal(elements.note.textContent,'New packet');});
test('Malformed complete state does not replace the interface',()=>{c.statepacket(11,0,1,'bad');c.statepacket(12,0,1,encodeURIComponent('{"mode":"left"}'));assert.equal(elements.note.textContent,'New packet');});
test('Light and dark Live themes derive readable card/background borders',()=>{const themed={...base,colors:{live_lcd_bg:[.9,.9,.9,1],live_control_fg:[.1,.1,.1,1],live_lcd_control_fg:[1,.6,.2,1]}};state(themed,13);assert.equal(props['--bg'],'rgba(230,230,230,1)');assert(props['--panel'].startsWith('rgba(213,213,213'));state({...themed,colors:{live_lcd_bg:[.1,.1,.1,1],live_control_fg:[.9,.9,.9,1]}},14);assert.equal(props['--bg'],'rgba(26,26,26,1)');assert(props['--panel'].startsWith('rgba(42,42,42'));});
test('Card recording/action commands and model/file controls use the bridge',()=>{elements['card-middle'].querySelector('.record').onclick();assert.deepEqual(JSON.parse(decodeURIComponent(sent.at(-1)[1])),{op:'record',label:'middle'});const select=elements['card-ok'].querySelector('select');select.value='gate';select.onchange();assert.deepEqual(JSON.parse(decodeURIComponent(sent.at(-1)[1])),{op:'action',index:5,value:'gate'});elements.importModel.onclick();assert.equal(JSON.parse(decodeURIComponent(sent.at(-1)[1])).op,'import');});
fs.writeFileSync(path.join(__dirname,'../validation/ui.json'),JSON.stringify({kind:'Actual HTML functions executed with a minimal simulated DOM; no browser/Live render',checks},null,2)+'\n');console.log(checks.length+' UI function checks passed');
