const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');const checks=[];
function fixture(surface){const html=fs.readFileSync(path.join(__dirname,'../Glove_Gesture/gesture_'+surface+'.html'),'utf8'),ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);const elements={},props={},sent=[];function E(){this.dataset={};this.children=[];this.selectors={};this._text='';}Object.defineProperty(E.prototype,'textContent',{get(){return this._text;},set(v){this._text=v;this.children=[];}});E.prototype.appendChild=function(e){this.children.push(e);if(e.id)elements[e.id]=e;};E.prototype.querySelector=function(s){return this.selectors[s]||(this.selectors[s]=new E());};ids.forEach(id=>elements[id]=new E());const c={window:{max:{outlet:(...a)=>sent.push(a),bindInlet:()=>{}}},document:{activeElement:null,documentElement:{style:{setProperty:(k,v)=>props[k]=v}},getElementById:id=>elements[id],createElement:()=>new E()}};vm.createContext(c);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],c);let seq=0;return {c,e:elements,props,sent,html,receive:s=>c.statepacket(++seq,0,1,encodeURIComponent(JSON.stringify(s))),next:()=>++seq};}
const labels=['open','fist','index','v','middle','ok'];const pairs=labels.flatMap(l=>labels.map(r=>l+'__'+r));function state(mode='left'){return {mode,selections:{left:'open',right:'fist'},selectedLabel:mode==='both'?'open__fist':mode==='right'?'fist':'open',classKeys:mode==='both'?pairs:labels,ready:true,engineReady:true,running:false,training:false,recording:null,counts:Array(mode==='both'?37:7).fill(40),enabled:Array(mode==='both'?36:6).fill(true),trained:true,hold:120,cooldown:350,radius:.18,epochs:500,pulse:120,actions:Array(48).fill('toggle'),targets:Array(48).fill(''),note:'Ready',candidate:'other',confirmed:null,colors:{},models:[],modelSelection:'',learning:-1,allCounts:{left:Array(7).fill(40),right:Array(7).fill(40),both:Array(37).fill(0)},allEnabled:{left:Array(6).fill(true),right:Array(6).fill(true),both:Array(36).fill(false)}};}
function test(n,fn){fn();checks.push(n);}
test('Main surface contains one pose area, six-choice dropdowns and a separate Mapping button',()=>{const f=fixture('ui');assert(!f.html.includes('class="cards"'));assert.equal(f.e.leftGesture.children.length,6);assert.equal(f.e.rightGesture.children.length,6);assert.equal((f.e.poseArt.innerHTML.match(/<svg/g)||[]).length,1);f.e.mapping.onclick();assert.equal(JSON.parse(decodeURIComponent(f.sent.at(-1)[1])).op,'mapping');});
test('Single-hand modes show only their training dropdown and correct mirrored image',()=>{const f=fixture('ui');f.receive(state());assert(f.e.rightLabel.hidden);assert(!f.e.leftLabel.hidden);assert(f.e.poseArt.innerHTML.includes('hand left'));f.receive(state('right'));assert(f.e.leftLabel.hidden);assert(f.e.poseArt.innerHTML.includes('hand right'));assert.equal(f.e.poseTitle.textContent,'Fist');assert(f.html.includes('[hidden]{display:none!important}'));});
test('Both mode independently selects and displays two different poses in one combination',()=>{const f=fixture('ui');f.receive(state('both'));assert(!f.e.leftLabel.hidden&&!f.e.rightLabel.hidden);assert.equal((f.e.poseArt.innerHTML.match(/<svg/g)||[]).length,2);assert.equal(f.e.poseTitle.textContent,'L Open hand + R Fist');f.e.rightGesture.value='v';f.e.rightGesture.onchange();assert.deepEqual(JSON.parse(decodeURIComponent(f.sent.at(-1)[1])),{op:'selectGesture',hand:'right',value:'v'});});
test('Run displays the detected pose and distinguishes confirming from confirmed',()=>{const f=fixture('ui');f.receive({...state(),running:true,candidate:'middle'});assert.equal(f.e.poseTitle.textContent,'Middle');assert.equal(f.e.poseStatus.textContent,'CONFIRMING…');f.receive({...state(),running:true,candidate:'middle',confirmed:'middle'});assert.equal(f.e.poseStatus.textContent,'CONFIRMED');assert(f.e.pose.className.includes('live'));f.receive({...state('both'),running:true,candidate:'fist__v',confirmed:'fist__v'});assert.equal(f.e.poseTitle.textContent,'L Fist + R V sign');});
test('Other shows an unknown marker, never a misleading previous hand pose',()=>{const f=fixture('ui');f.receive({...state(),running:true,candidate:'other'});assert(!f.e.poseArt.innerHTML.includes('<svg'));assert.equal(f.e.poseStatus.textContent,'OTHER / TRANSITION');});
test('Native readiness, recording and model compatibility gate controls',()=>{const f=fixture('ui');f.receive({...state(),engineReady:false});assert(f.e.run.disabled&&f.e.train.disabled);f.receive({...state(),recording:'open'});assert(f.e.leftGesture.disabled&&f.e.run.disabled);f.receive({...state(),training:true});assert.equal(f.e.train.textContent,'Cancel');assert(!f.e.train.disabled);f.receive({...state(),models:[{id:'m',name:'中文',mode:'both'}],modelSelection:'m'});assert(f.e.loadModel.disabled);assert(!f.e.exportModel.disabled);});
test('Fragmented/out-of-order/stale packets and malformed states preserve the interface',()=>{const f=fixture('ui');f.receive(state());const seq=f.next(),encoded=encodeURIComponent(JSON.stringify({...state(),note:'Fragmented'})),parts=encoded.match(/.{1,120}/g);for(let i=parts.length-1;i>=0;i--)f.c.statepacket(seq,i,parts.length,parts[i]);assert.equal(f.e.note.textContent,'Fragmented');f.c.statepacket(seq-1,0,1,encodeURIComponent(JSON.stringify(state())));f.c.statepacket(f.next(),0,1,'invalid');assert.equal(f.e.note.textContent,'Fragmented');});
test('Shared theme logic derives readable light and dark panels',()=>{const f=fixture('ui');f.receive({...state(),colors:{live_lcd_bg:[.9,.9,.9,1],live_control_fg:[.1,.1,.1,1]}});assert(f.props['--panel'].startsWith('rgba(213'));f.receive({...state(),colors:{live_lcd_bg:[.1,.1,.1,1],live_control_fg:[.9,.9,.9,1]}});assert(f.props['--panel'].startsWith('rgba(42'));});
test('Mapping window lists independent Left/Right rows and sends native learn commands',()=>{const f=fixture('mapping');f.receive(state());assert.equal(f.e.rows.children.length,6);f.e.rows.children[0].querySelector('.map').onclick();assert.equal(JSON.parse(decodeURIComponent(f.sent.at(-1)[1])).index,0);f.e.view.value='right';f.e.view.onchange();f.e.rows.children[0].querySelector('.map').onclick();assert.equal(JSON.parse(decodeURIComponent(f.sent.at(-1)[1])).index,6);});
test('Combined mapping view filters recorded pairs or exposes all 36 ordered combinations',()=>{const f=fixture('mapping'),s=state('both');s.allCounts.both[9]=40;s.allEnabled.both[9]=true;f.receive(s);assert.equal(f.e.rows.children.length,1);assert.equal(f.e.rows.children[0].querySelector('.title').textContent,'L Fist + R V sign');f.e.rows.children[0].querySelector('.map').onclick();assert.equal(JSON.parse(decodeURIComponent(f.sent.at(-1)[1])).index,21);f.e.all.checked=true;f.e.all.onchange();assert.equal(f.e.rows.children.length,36);});
test('Mapping armed state, target names and per-row actions update independently',()=>{const f=fixture('mapping'),s=state();s.targets[0]='Device On';s.learning=0;s.actions[0]='pulse';f.receive(s);const row=f.e.rows.children[0];assert.equal(row.querySelector('.target').textContent,'Device On');assert.equal(row.querySelector('.map').textContent,'Click Live');assert.equal(row.querySelector('.action').value,'pulse');});
fs.writeFileSync(path.join(__dirname,'../validation/ui.json'),JSON.stringify({kind:'Actual main/mapping HTML functions with simulated DOM; no browser or Live render',checks},null,2)+'\n');console.log(checks.length+' main/mapping UI checks passed');
