var GestureUI=(function(){
 var icons=__GESTURE_ICONS__,labels=['open','fist','index','v','middle','ok'],names=['Open hand','Fist','Index','V sign','Middle','OK'];
 function keys(mode){var a=[];if(mode==='both')labels.forEach(function(l){labels.forEach(function(r){a.push(l+'__'+r);});});else a=labels.slice();return a;}
 function parts(key){return key.indexOf('__')>=0?key.split('__'):[key,key];}
 function title(key,mode){if(key==='other'||!key)return 'Other / transition';var p=parts(key);return mode==='both'?'L '+names[labels.indexOf(p[0])]+' + R '+names[labels.indexOf(p[1])]:names[labels.indexOf(key)];}
 function slot(mode,key){return (mode==='left'?0:mode==='right'?6:12)+keys(mode).indexOf(key);}
 function image(key,mode){if(!key||key==='other')return '<span class="unknown">?</span>';var p=parts(key);return mode==='both'?'<span class="hand left">'+icons[p[0]]+'</span><span class="plus">+</span><span class="hand right">'+icons[p[1]]+'</span>':'<span class="hand '+mode+'">'+icons[key]+'</span>';}
 function send(op,fields){var m=Object.assign({op:op},fields||{});if(window.max&&window.max.outlet)window.max.outlet('command',encodeURIComponent(JSON.stringify(m)));}
 function rgb(v){return 'rgba('+v.slice(0,3).map(function(x){return Math.round(Math.max(0,Math.min(1,x))*255);}).join(',')+','+Math.max(0,Math.min(1,v[3]))+')';}
 function theme(c){var map={live_lcd_bg:'--bg',live_control_text_bg:'--field',live_control_fg:'--ink',live_lcd_control_fg:'--accent',live_lcd_control_fg_zombie:'--muted'};Object.keys(map).forEach(function(k){var v=c[k];if(Array.isArray(v)&&v.length===4&&v.every(Number.isFinite))document.documentElement.style.setProperty(map[k],rgb(v));});var bg=c.live_lcd_bg,ink=c.live_control_fg;if(Array.isArray(bg)&&Array.isArray(ink)&&bg.length===4&&ink.length===4&&bg.concat(ink).every(Number.isFinite)){document.documentElement.style.setProperty('--panel',rgb(bg.map(function(v,i){return i===3?1:v*.92+ink[i]*.08;})));document.documentElement.style.setProperty('--line',rgb(bg.map(function(v,i){return i===3?1:v*.68+ink[i]*.32;})));}}
 function value(id,v){var e=document.getElementById(id);if(document.activeElement!==e)e.value=String(v);}
 function receiver(render){var last=-1,p=null;return function(seq,index,total,part){seq=Number(seq);index=Number(index);total=Number(total);if(!Number.isInteger(seq)||!Number.isInteger(index)||!Number.isInteger(total)||seq<=last||index<0||index>=total||total<1||total>2048||typeof part!=='string')return;if(!p||seq>p.seq)p={seq:seq,total:total,parts:new Array(total),count:0};if(seq!==p.seq||total!==p.total||p.parts[index]!==undefined)return;p.parts[index]=part;if(++p.count!==total)return;try{var s=JSON.parse(decodeURIComponent(p.parts.join(''))),n=s.mode==='both'?36:6;if(!s||['left','right','both'].indexOf(s.mode)<0||!Array.isArray(s.counts)||s.counts.length!==n+1||!Array.isArray(s.enabled)||s.enabled.length!==n||!Array.isArray(s.actions)||s.actions.length!==48||!Array.isArray(s.targets)||s.targets.length!==48||!Array.isArray(s.models)||!s.selections||labels.indexOf(s.selections.left)<0||labels.indexOf(s.selections.right)<0)throw Error('Malformed state');render(s);last=seq;}catch(e){}p=null;};}
 return {labels:labels,names:names,keys:keys,parts:parts,title:title,slot:slot,image:image,send:send,theme:theme,value:value,receiver:receiver};
}());
