const N=require('./model_format.js'),fs=require('fs'),path=require('path'),assert=require('assert');
const checks=[];function test(name,fn){fn();checks.push({name,pass:true});}
const model={layers:[{rows:5,cols:3,activation:3,biases:[.1,-.2,.3],weights:Array.from({length:5},()=>[.1,.2,-.1])},{rows:3,cols:10,activation:0,biases:Array(10).fill(.3),weights:Array.from({length:3},()=>Array(10).fill(.1))}]};
test('FluCoMa layer format validates and serializes without changing weights',()=>{N.validate(model,5,10);assert.deepEqual(N.fromFluCoMa(model,5,10).model,model);});
test('All four native FluCoMa activation codes are accepted',()=>{for(const activation of [0,1,2,3]){const m=N.copy(model);m.layers[0].activation=activation;N.validate(m,5,10);}});
test('Layer, input and output dimensional mismatches are rejected',()=>{assert.throws(()=>N.validate(model,10,10));assert.throws(()=>N.validate(model,5,9));const m=N.copy(model);m.layers[0].weights[0].pop();assert.throws(()=>N.validate(m,5,10));});
test('Non-finite weights, invalid activation and malformed input are rejected',()=>{const m=N.copy(model);m.layers[0].weights[0][0]=NaN;assert.throws(()=>N.validate(m,5,10));const n=N.copy(model);n.layers[0].activation=4;assert.throws(()=>N.validate(n,5,10));assert.throws(()=>N.vector([0,0,'0',0,0],5));assert.throws(()=>N.vector([0,0,NaN,0,0],5));assert.deepEqual(N.vector([-1,0,.5,1,2],5),[0,0,.5,1,1]);});
test('User-selected Data Knot JSON retains weights and paired examples',()=>{const d={fits:{input_regressor:model},data:{datasets:{input:{data:{a:[0,0,0,0,0],b:[1,1,1,1,1]}},output:{data:{a:Array(10).fill(.3),b:Array(10).fill(.5)}}}}};const b=N.fromDataKnot(d,5,10);assert.equal(b.samples.length,2);assert.deepEqual(b.model,model);assert.throws(()=>N.fromDataKnot(d,10,10));});
test('JavaScript utility exposes no neural trainer or predictor',()=>{assert(!N.Trainer);assert(!N.predict);assert(!N.forward);});
fs.writeFileSync(path.join(__dirname,'../validation/format.json'),JSON.stringify({kind:'Model schema/serialization checks; no neural math in JavaScript',checks},null,2));console.log(checks.length+' format checks passed');
