const N=require('./neural_core.js'),fs=require('fs'),path=require('path'),assert=require('assert');
const checks=[];function test(name,fn){fn();checks.push({name,pass:true});}
const synthetic={fits:{input_regressor:{layers:[{rows:5,cols:3,activation:3,biases:[.1,-.2,.3],weights:Array.from({length:5},(_,i)=>[.1+i/10,.2-i/20,-.1])},{rows:3,cols:10,activation:0,biases:Array(10).fill(.3),weights:Array.from({length:3},(_,i)=>Array.from({length:10},(_,j)=>.1*Math.sin(i+j)))}]}},data:{datasets:{input:{data:{a:[0,0,0,0,0],b:[1,1,1,1,1]}},output:{data:{a:Array(10).fill(.3),b:Array(10).fill(.5)}}}}};
test('User-selected Data Knot layer format imports without a bundled preset',()=>{const b=N.fromDataKnot(synthetic,5,10);assert.equal(b.samples.length,2);assert.deepEqual(b.model.layers.map(l=>[l.rows,l.cols,l.activation]),[[5,3,3],[3,10,0]]);});
test('Neural output agrees with independently accumulated tanh/linear layers',()=>{const b=N.fromDataKnot(synthetic,5,10);for(const x of [[.1,.2,.3,.4,.5],[1,0,.4,.7,.2]]){let a=x;for(const l of b.model.layers)a=l.biases.map((bias,j)=>{const z=bias+a.reduce((v,x,i)=>v+x*l.weights[i][j],0);return l.activation===3?Math.tanh(z):z;});const y=N.predict(b.model,x);a.forEach((v,j)=>assert(Math.abs(Math.max(0,Math.min(1,v))-y[j])<1e-12));}});
test('Data Knot input and output dimensions cannot silently change',()=>{assert.throws(()=>N.fromDataKnot(synthetic,10,10),/requires/);assert.throws(()=>N.fromDataKnot(synthetic,5,11),/requires/);});
test('Input validation rejects incomplete, string and non-finite values and clips range',()=>{assert.throws(()=>N.vector([0,0],5));assert.throws(()=>N.vector([0,0,'0',0,0],5));assert.throws(()=>N.vector([0,0,NaN,0,0],5));assert.deepEqual(N.vector([-1,0,.5,1,2],5),[0,0,.5,1,1]);});
test('Invalid weight dimensions and unsupported activations are rejected',()=>{const b=N.fromDataKnot(synthetic,5,10);b.model.layers[0].weights[0].pop();assert.throws(()=>N.validate(b.model,5,10));const c=N.fromDataKnot(synthetic,5,10);c.model.layers[0].activation=9;assert.throws(()=>N.validate(c.model,5,10));});
test('Adam backprop learns a synthetic single-hand ten-output mapping',()=>{const samples=[];for(let i=0;i<30;i++){const x=Array.from({length:5},(_,j)=>((i*13+j*17)%101)/100);samples.push({x,y:Array.from({length:10},(_,j)=>.5+.3*Math.sin(x[j%5]*1.5+x[(j+1)%5]))});}const t=new N.Trainer(samples,5,10,800);while(!t.advance()){}assert(t.loss<.035,'RMSE '+t.loss);N.validate(t.model,5,10);checks.push({name:'Synthetic single-hand training RMSE',value:t.loss,pass:true});});
test('Ten-input model learns a nonlinear two-hand mapping',()=>{const samples=[];for(let i=0;i<30;i++){const x=Array.from({length:10},(_,j)=>((i*13+j*17)%101)/100);samples.push({x,y:[x[0]*x[5],.5+.35*Math.sin(x[1]*2-x[8])]});}const t=new N.Trainer(samples,10,2,800);while(!t.advance()){}assert(t.loss<.025,'RMSE '+t.loss);N.validate(t.model,10,2);checks.push({name:'Synthetic two-hand training RMSE',value:t.loss,pass:true});});
test('Training needs two examples; serialized weights predict identically',()=>{assert.throws(()=>new N.Trainer([{x:[0,0,0,0,0],y:[0]}],5,1,800));const m=N.fromDataKnot(synthetic,5,10).model,x=[.1,.2,.3,.4,.5];assert.deepEqual(N.predict(m,x),N.predict(JSON.parse(JSON.stringify(m)),x));});
fs.mkdirSync(path.join(__dirname,'../validation'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../validation/neural.json'),JSON.stringify({kind:'Executed shipped pure ES5 neural core in Node; synthetic data only',checks},null,2));console.log(checks.length+' neural checks passed');
