// Deterministic VM tests of the actual Max JS engine; no live hardware required.
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const file=__dirname+'/../glove_midi_trigger.js';let passed=0;
function host(){let time=1000,out=[],math=Object.create(Math);math.random=()=>.37;
 const c={Date:{now:()=>time},Math:math,isFinite,inlet:0,arrayfromargs:a=>Array.from(a),
  outlet:(n,a)=>out.push([n,Array.from(a)]),Task:function(fn){this.interval=0;this.cancel=()=>{};this.repeat=()=>{};this.fn=fn;}};
 vm.createContext(c);vm.runInContext(fs.readFileSync(file,'utf8'),c);c.start();out=[];
 return {c,out,step(ms=20){time+=ms;c.tick();},frame(hand,values,ms=20){time+=ms;c[hand](...values);c.tick();},
  get time(){return time;},midi(){return out.filter(x=>x[0]===0).map(x=>x[1]);},clear(){out.length=0;}};}
function check(name,fn){fn();passed++;console.log('PASS '+name);}
function neutral(h){h.frame('left',[0,0,0,0,0]);h.frame('left',[0,0,0,0,0]);h.clear();}
function hit(h,x=1){h.frame('left',[x,0,0,0,0]);h.frame('left',[x,0,0,0,0]);h.step(20);}
function on(h){return h.midi().filter(a=>(a[0]&240)===144);}
function off(h){return h.midi().filter(a=>(a[0]&240)===128);}
check('constant pose and tiny noise do not trigger',()=>{let h=host();neutral(h);for(let i=0;i<100;i++)h.frame('left',[i%2?.001:0,0,0,0,0]);assert.equal(on(h).length,0);});
check('acceleration emits timed note and respects velocity bounds',()=>{let h=host();h.c.config(0,'vmin',40);h.c.config(0,'vmax',90);neutral(h);hit(h);assert.equal(on(h).length,1);assert(on(h)[0][2]>=40&&on(h)[0][2]<=90);h.step(121);assert.equal(off(h).length,1);});
check('higher acceleration produces higher velocity',()=>{let a=host(),b=host();a.c.setting('reference',500);b.c.setting('reference',500);neutral(a);neutral(b);hit(a,.3);hit(b,1);assert.equal(on(a).length,1);assert.equal(on(b).length,1);assert(on(b)[0][2]>on(a)[0][2]);});
check('sensitivity changes threshold response',()=>{let a=host(),b=host();a.c.setting('reference',500);b.c.setting('reference',500);a.c.setting('sensitivity',10);b.c.setting('sensitivity',400);neutral(a);neutral(b);hit(a,.3);hit(b,.3);assert.equal(on(a).length,0);assert.equal(on(b).length,1);});
check('stable hold creates one note, pressure updates, hysteresis releases',()=>{let h=host();h.c.config(0,'mode',1);neutral(h);h.frame('left',[.6,0,0,0,0]);assert.equal(on(h).length,1);for(let i=0;i<5;i++)h.frame('left',[.9,0,0,0,0]);assert.equal(on(h).length,1);assert(h.midi().some(a=>(a[0]&240)===160&&a[2]>70));h.frame('left',[.48,0,0,0,0]);assert.equal(off(h).length,0);h.frame('left',[.44,0,0,0,0]);assert.equal(off(h).length,1);});
check('starting bent does not create a held note until neutral',()=>{let h=host();h.c.config(0,'mode',1);h.frame('left',[.9,0,0,0,0]);h.frame('left',[.9,0,0,0,0]);assert.equal(on(h).length,0);h.frame('left',[0,0,0,0,0]);h.frame('left',[.7,0,0,0,0]);assert.equal(on(h).length,1);});
check('two hands are independent and use documented finger order',()=>{let h=host();h.c.config(0,'mode',1);h.c.config(9,'mode',1);neutral(h);h.frame('right',[0,0,0,0,0]);h.frame('left',[.7,0,0,0,0]);h.frame('right',[0,0,0,0,.7]);assert.deepEqual(on(h).map(x=>x[1]),[60,69]);});
check('shared pitch releases only after the final owner',()=>{let h=host();h.c.config(0,'mode',1);h.c.config(1,'mode',1);h.c.config(1,'note',60);neutral(h);h.frame('left',[.7,.8,0,0,0]);assert.equal(on(h).length,1);h.frame('left',[0,.8,0,0,0]);assert.equal(off(h).length,0);h.frame('left',[0,0,0,0,0]);assert.equal(off(h).length,1);assert.equal(Object.keys(h.c.voices).length,0);});
check('hold timeout releases, reconnect requires neutral',()=>{let h=host();h.c.config(0,'mode',1);neutral(h);h.frame('left',[.7,0,0,0,0]);h.step(251);assert.equal(off(h).length,1);h.frame('left',[.7,0,0,0,0]);assert.equal(on(h).length,1);});
check('100 ms frame gap resets derivatives and releases hold',()=>{let h=host();h.c.config(0,'mode',1);neutral(h);h.frame('left',[.7,0,0,0,0]);h.frame('left',[.7,0,0,0,0],101);assert.equal(off(h).length,1);assert.equal(on(h).length,1);});
check('channel change releases on the original channel',()=>{let h=host();h.c.config(0,'mode',1);neutral(h);h.frame('left',[.7,0,0,0,0]);h.c.setting('channel',3);assert.deepEqual(off(h)[0],[128,60,0]);h.frame('left',[0,0,0,0,0]);h.frame('left',[.7,0,0,0,0]);assert.equal(on(h).at(-1)[0],146);});
check('disable, config change, panic and deletion release notes',()=>{for(let action of [c=>c.device(0),c=>c.config(0,'on',0),c=>c.config(0,'mode',0),c=>c.panic(),c=>c.notifydeleted()]){let h=host();h.c.config(0,'mode',1);neutral(h);h.frame('left',[.7,0,0,0,0]);action(h.c);assert.equal(off(h).length,1);}});
check('disabled device cannot generate notes',()=>{let h=host();h.c.device(0);neutral(h);hit(h);assert.equal(on(h).length,0);});
check('random candidate sets cover all scales and roots within inclusive bounds',()=>{let h=host();for(let scale=0;scale<12;scale++)for(let root=0;root<12;root++){let c={scale,root,low:50,high:74,pitchmode:1};let a=h.c.candidates(c);assert(a.length);for(let n of a){assert(n>=50&&n<=74);assert(h.c.scales[scale].includes((n-root+120)%12));}for(let i=0;i<30;i++)assert(a.includes(h.c.choose(c)));}});
check('empty random ranges never emit an out-of-range fallback',()=>{let h=host();h.c.config(0,'pitchmode',1);h.c.config(0,'low',61);h.c.config(0,'high',61);neutral(h);hit(h);assert.equal(on(h).length,0);h.c.config(0,'low',80);h.c.config(0,'high',40);assert.equal(h.c.candidates(h.c.fingers[0].config).length,0);});
check('fixed pitch includes MIDI endpoints 0 and 127',()=>{let h=host();assert.equal(h.c.choose({pitchmode:0,note:0}),0);assert.equal(h.c.choose({pitchmode:0,note:127}),127);});
check('velocity endpoints support normal and inverse ranges; never zero',()=>{let h=host();assert.equal(h.c.velocity({vmin:20,vmax:110},0),20);assert.equal(h.c.velocity({vmin:20,vmax:110},1),110);assert.equal(h.c.velocity({vmin:110,vmax:20},1),20);h.c.config(0,'vmin',0);assert.equal(h.c.fingers[0].config.vmin,1);});
check('invalid and duplicate-time frames cannot spike acceleration',()=>{let h=host();neutral(h);let last=h.c.hands[0].last;h.c.left(0,NaN,0,0,0);h.c.left(2,0,0,0,0);h.c.left(0,0);assert.equal(h.c.hands[0].last,last);for(let i=0;i<20;i++)h.c.left(1,0,0,0,0);assert.equal(on(h).length,0);assert(Number.isFinite(h.c.fingers[0].state.a));});
check('all 10 fingers can emit and release MIDI in both modes',()=>{for(let mode of [0,1]){let h=host();for(let i=0;i<10;i++)h.c.config(i,'mode',mode);h.frame('left',[0,0,0,0,0]);h.frame('right',[0,0,0,0,0]);h.frame('left',[0,0,0,0,0]);h.frame('right',[0,0,0,0,0]);h.clear();h.frame('left',[.9,.9,.9,.9,.9]);h.frame('right',[.9,.9,.9,.9,.9]);h.step(20);assert.equal(on(h).length,10);h.c.panic();assert.equal(off(h).length,10);}});
check('retrigger interval prevents rapid note bursts',()=>{let h=host();h.c.setting('gap',400);neutral(h);for(let i=0;i<12;i++)h.frame('left',[i%2?0:1,0,0,0,0]);assert(on(h).length<=1);});
check('calibration captures motion and emits one persisted reference without notes',()=>{let h=host();neutral(h);h.c.calibrate();for(let i=0;i<400;i++)h.frame('left',[i%10<5?1:0,0,0,0,0]);assert.equal(on(h).length,0);let refs=h.out.filter(x=>x[0]===2);assert.equal(refs.length,1);assert(refs[0][1][1]>.1);});
check('silent calibration keeps the prior reference',()=>{let h=host();neutral(h);h.c.setting('reference',77);h.c.calibrate();for(let i=0;i<400;i++)h.frame('left',[0,0,0,0,0]);assert.equal(h.c.globals.reference,77);assert.equal(h.out.filter(x=>x[0]===2).length,0);});
check('calibration can be cancelled and a configuration is serializable',()=>{let h=host();h.c.calibrate();h.c.calibrate();assert.equal(h.c.calibrating,null);assert.equal(JSON.parse(JSON.stringify(h.c.fingers[0].config)).note,60);});
check('MIDI running status / channel, pressure, bend and realtime thru',()=>{let h=host();h.c.inlet=1;[144,60,100,61,90,248,128,60,0,192,4,5,224,0,64,160,60,70].forEach(v=>h.c.msg_int(v));assert.deepEqual(h.midi(),[[144,60,100],[144,61,90],[248],[128,60,0],[192,4],[192,5],[224,0,64],[160,60,70]]);});
check('system common clears running status, SysEx stays a complete packet',()=>{let h=host();h.c.inlet=1;[144,60,100,242,1,2,61,90,240,1,2,248,3,247].forEach(v=>h.c.msg_int(v));assert.deepEqual(h.midi(),[[144,60,100],[242,1,2],[248],[240,1,2,3,247]]);});
check('unchanged UI state does not redraw every tick',()=>{let h=host();neutral(h);h.clear();for(let i=0;i<5;i++)h.frame('left',[0,0,0,0,0]);assert.equal(h.out.filter(x=>x[0]===1).length,0);});
console.log(`${passed} engine checks passed.`);
